environment:
   PHP_VERSION: 5.6.12

os: 
  - Visual Studio 2015

configuration: Release

version: '0.0.{build}'

matrix:
  fast_finish: true

install:
  - cd C:\projects\sassphp
  - git submodule init
  - git submodule update
  - cd C:\
  - mkdir php-src
  - echo Preparing Windows build...
  - echo Downloading PHP source code [%PHP_VERSION%]
  - cd C:\php-src
  - appveyor DownloadFile http://windows.php.net/downloads/releases/php-5.6.12-src.zip -FileName php-src.zip
  - 7z x -y php-src.zip > nul
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

build_script: 
  - cd C:\php-src\php-5.6.12-src
  - buildconf.bat --add-modules-dir=C:\projects
  - configure --disable-all --enable-cli --enable-sass
  - nmake php_sass.dll

test: OFF

test_script: OFF

deploy: OFF

notifications:
  - on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

artifacts:
  - path: ext\Release_TS\php_sass.dll